import Head from "next/head";
import HomeContainer from "../features/Home/Container";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Sofia&effect=fire"
        />
      </Head>

      <main>
        <HomeContainer />
      </main>
    </div>
  );
}
